### ISSUE TITLE
ng-model-options debounce is ignored

### ISSUE THREAD

**Issue by seishin4real** [angular-redux/form#11]
I specified ng-model-options:
`<input type="text" class="form-control" name="question1" ngControl ngModel ng-model-options="{ debounce : { default : 1500, blur : 0 } }"/>`
but FORM_CHANGED action is dispatched on every keystroke.

**Comment by e-schultz** [comment]
The `ngModelOptions` that is part of Angular 2+ is very different than the Angular 1.x version. 

ngModelOptions in Angular 2+, only indicate the name, and if it's a standalone element or not, [and the docs are not very clear on what this actually does](https://angular.io/docs/ts/latest/api/forms/index/NgModel-directive.html#!#options-anchor) 

I wish that the ng-model-options was closer to the Angular 1.x counterpart.

**Comment by JohannesHoppe** [comment]
Similar request here, on every input-field-keystroke I get a new action ([see here](https://github.com/angular-redux/form/blob/master/source/connect.ts#L84)).
A little bit chatty, isn't it?

Could we get something like 
```
(<any>this.form.valueChanges)
      .debounceTime(500)
      .distinctUntilChanged()
```
into the code?
