### ISSUE TITLE
CORS for mocky.io

### ISSUE THREAD

**Issue by atodd-geoplan** [angular-redux/form#13]
Trying to run the examples - Chrome is complaining about CORS from mocky.io:

> XMLHttpRequest cannot load http://www.mocky.io/v2/588d702d100000d50f2d2980. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

I note that it is only on the intial load, the app routes to `/elephants` and this is where the error occurs.

Subsequent clicks to `elephants `is fine.

**Comment by SethDavenport** [comment]
is this still happening? could have sworn I fixed it...

**Comment by atodd-geoplan** [comment]
No it works something wrong with my local set up, So I closed this...

**Comment by SethDavenport** [comment]
Ok cool - thanks.
