### ISSUE TITLE
compilation error in connect-array.ts

### ISSUE THREAD

**Issue by gorshkov-leonid** [angular-redux/form#19]
![screenshot_16](https://cloud.githubusercontent.com/assets/2270831/24683664/9e9a851a-19b1-11e7-89af-be368fef50ba.png)

**Comment by gorshkov-leonid** [comment]
I think best practice is to publish d.ts and js

**Comment by gorshkov-leonid** [comment]
could you compile with aggressive compiler options. https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md , noImplicitAny and etc

**Comment by smithad15** [comment]
I believe this has been fixed and stricter compiler options have been enabled. Please open a new issue if you are still having problems.
