### ISSUE TITLE
CombineReducers throwing an error when using connect directive

### ISSUE THREAD

**Issue by ghost** [angular-redux/form#39]
https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L47 in combineReducers is causing an issue as it does not recognize newly added form state keys

**Comment by smithad15** [comment]
This is also mentioned in #6. The library still works, however because it is injecting a new key into the root state, `combineReducers` doesn't like that. It's on the list to fix for v7 but you should be still good to use it for now.
