### ISSUE TITLE
Support for Angular 5+

### ISSUE THREAD

**Issue by mengel188** [angular-redux/form#47]
### This is a...

* [ x] feature request
* [ ] bug report
* [ ] usage question

### Additional Notes:
Currently this project does not support Angular 5.0.
Is there any pre-release that does?

What do we need to change to implement the support?

**Comment by actra-gschuster** [comment]
What doesn't work for you?
I'm running it on 5.1.0-beta.0, despite from reative forms not working (a fix is in the PRs: #48 ) it works for me.

**Comment by mengel188** [comment]
So far it works fine for me but I'm only using template driven forms. Can you please get the peerDependencies updated to inculde ^5.0.0? Much appreciated.

**Comment by smithad15** [comment]
Peer dependencies and reactive forms fixed as of v6.7.0. Will release v7 shortly built using the Angular 5 compiler
